#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import pandas as pd
import json
import re
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

# In[ ]:


# match of the package features between train and test data set
# for the ease of the managebility, Russian version will be main

feat_dict = {'android-auto': 'Android Auto',
 'aux': 'AUX',
 'bluetooth': 'Bluetooth',
 'apple-carplay': 'CarPlay',
 'usb': 'USB',
 'automatic-lighting-control': 'Автоматический корректор фар',
 'auto-cruise': 'Адаптивный круиз-контроль',
 'activ-suspension': 'Активная подвеска',
 'servo': 'Активный усилитель руля',
 'alcantara': 'Алькантара (Материал салона)',
 'abs': 'Антиблокировочная система (ABS)',
 'asr': 'Антипробуксовочная система (ASR)',
 'audiopreparation': 'Аудиоподготовка',
 'audiosystem-cd': 'Аудиосистема',
 'music-super': 'Аудиосистема Hi-Fi',
 'audiosystem-tv': 'Аудиосистема с TV',
 'airbrush': 'Аэрография',
 'wireless-charger': 'Беспроводная зарядка для смартфона',
 'power-child-locks-rear-doors': 'Блокировка замков задних дверей',
 'computer': 'Бортовой компьютер',
 'armored': 'Бронированный кузов',
 'velvet-seats': 'Велюр (Материал салона)',
 'rear-seat-heat-vent': 'Вентиляция задних сидений',
 'front-seats-heat-vent': 'Вентиляция передних сидений',
 'driver-seat-support': 'Водительское сиденье с поясничной поддержкой',
 'gbo': 'Газобаллонное оборудование',
 'voice-recognition': 'Голосовое управление',
 'tyre-pressure': 'Датчик давления в шинах',
 'rain-sensor': 'Датчик дождя',
 'volume-sensor': 'Датчик проникновения в салон (датчик объема)',
 'light-sensor': 'Датчик света',
 'drowsy-driver-alert-system': 'Датчик усталости водителя',
 'decorative-interior-lighting': 'Декоративная подсветка салона',
 'body-mouldings': 'Декоративные молдинги',
 'sport-pedals': 'Декоративные накладки на педали',
 '14-inch-wheels': 'Диски 14',
 '15-inch-wheels': 'Диски 15',
 '16-inch-wheels': 'Диски 16',
 '17-inch-wheels': 'Диски 17',
 '18-inch-wheels': 'Диски 18',
 '19-inch-wheels': 'Диски 19',
 '20-inch-wheels': 'Диски 20',
 '21-inch-wheels': 'Диски 21',
 '22-inch-wheels': 'Диски 22',
 '27-inch-wheels': 'Диски 27',
 'remote-engine-start': 'Дистанционный запуск двигателя',
 'drl': 'Дневные ходовые огни',
 'power-latching-doors': 'Доводчик дверей',
 'reduce-spare-wheel': 'Докатка',
 'start-button': 'Запуск двигателя с кнопки',
 'engine-proof': 'Защита картера',
 'immo': 'Иммобилайзер',
 'eco-leather': 'Искусственная кожа (Материал салона)',
 '360-camera': 'Камера 360°',
 'rear-camera': 'Камера задняя',
 'front-camera': 'Камера передняя',
 'climate-control-1': 'Климат-контроль 1-зонный',
 'climate-control-2': 'Климат-контроль 2-зонный',
 'multizone-climate-control': 'Климат-контроль многозонный',
 'leather': 'Кожа (Материал салона)',
 'seats-2': 'Количество мест: 2',
 'seats-4': 'Количество мест: 4',
 'seats-5': 'Количество мест: 5',
 'seats-6': 'Количество мест: 6',
 'seats-7': 'Количество мест: 7',
 'combo-interior': 'Комбинированный (Материал салона)',
 'condition': 'Кондиционер',
 'isofix': 'Крепление детского кресла (задний ряд) ISOFIX',
 'isofix-front': 'Крепление детского кресла (передний ряд) ISOFIX',
 'cruise-control': 'Круиз-контроль',
 'xenon': 'Ксеноновые/Биксеноновые фары',
 'laser-lights': 'Лазерные фары',
 'laminated-safety-glass': 'Ламинированные боковые стекла',
 'alloy-wheel-disks': 'Легкосплавные диски',
 'hatch': 'Люк',
 'paint-metallic': 'Металлик',
 'entertainment-system-for-rear-seat-passengers': 'Мультимедиа система для задних пассажиров',
 'multi-wheel': 'Мультифункциональное рулевое колесо',
 'navigation': 'Навигационная система',
 'door-sill-panel': 'Накладки на пороги',
 'body-kit': 'Обвес кузова',
 'wheel-heat': 'Обогрев рулевого колеса',
 'light-cleaner': 'Омыватель фар',
 'wheel-leather': 'Отделка кожей рулевого колеса',
 'leather-gear-stick': 'Отделка кожей рычага КПП',
 'black-roof': 'Отделка потолка чёрной тканью',
 'easy-trunk-opening': 'Открытие багажника без помощи рук',
 'cooling-box': 'Охлаждаемый перчаточный ящик',
 'passenger-seat-memory': 'Память передних сидений',
 'seat-memory': 'Память передних сидений',
 'driver-seat-memory': 'Память сиденья водителя',
 'panorama-roof': 'Панорамная крыша / лобовое стекло',
 'park-assist-r': 'Парктроник задний',
 'park-assist-f': 'Парктроник передний',
 'front-seat-support': 'Передние сиденья с поясничной поддержкой',
 'front-centre-armrest': 'Передний центральный подлокотник',
 'air-suspension': 'Пневмоподвеска',
 'rear-seats-heat': 'Подогрев задних сидений',
 'front-seats-heat': 'Подогрев передних сидений',
 'steering-wheel-gear-shift-paddles': 'Подрулевые лепестки переключения передач',
 'airbag-driver': 'Подушка безопасности водителя',
 'knee-airbag': 'Подушка безопасности для защиты коленей водителя',
 'airbag-passenger': 'Подушка безопасности пассажира',
 'airbag-side': 'Подушки безопасности боковые',
 'airbag-rear-side': 'Подушки безопасности боковые задние',
 'airbag-curtain': 'Подушки безопасности оконные (шторки)',
 'spare-wheel': 'Полноразмерное запасное колесо',
 'ashtray-and-cigarette-lighter': 'Прикуриватель и пепельница',
 'programmed-block-heater': 'Программируемый предпусковой отопитель',
 'projection-display': 'Проекционный дисплей',
 'ptf': 'Противотуманные фары',
 'passenger-seat-updown': 'Регулировка передних сидений по высоте',
 'wheel-configuration2': 'Регулировка руля по вылету',
 'wheel-configuration1': 'Регулировка руля по высоте',
 'driver-seat-updown': 'Регулировка сиденья водителя по высоте',
 'adj-pedals': 'Регулируемый педальный узел',
 'roof-rails': 'Рейлинги на крыше',
 '12v-socket': 'Розетка 12V',
 '220v-socket': 'Розетка 220V',
 'wheel-memory': 'Рулевая колонка с памятью положения',
 'light-interior': 'Светлый салон',
 'led-lights': 'Светодиодные фары',
 'alarm': 'Сигнализация',
 'feedback-alarm': 'Сигнализация с обратной связью',
 'massage-seats': 'Сиденья с массажем',
 'start-stop-function': 'Система «старт-стоп»',
 'auto-park': 'Система автоматической парковки',
 'adaptive-light': 'Система адаптивного освещения',
 'drive-mode-sys': 'Система выбора режима движения',
 'keyless-entry': 'Система доступа без ключа',
 'lane-keeping-assist': 'Система контроля за полосой движения',
 'blind-spot': 'Система контроля слепых зон',
 'night-vision': 'Система ночного видения',
 'dha': 'Система помощи при спуске',
 'hcc': 'Система помощи при старте в гору (HSA)',
 'bas': 'Система помощи при торможении (BAS, EBD)',
 'collision-prevention-assist': 'Система предотвращения столкновения',
 'traffic-sign-recognition': 'Система распознавания дорожных знаков',
 'esp': 'Система стабилизации (ESP)',
 'vsm': 'Система стабилизации рулевого управления (VSM)',
 'high-beam-assist': 'Система управления дальним светом',
 'folding-tables-rear': 'Складной столик на спинках передних сидений',
 'seat-transformation': 'Складывающееся заднее сиденье',
 'roller-blind-for-rear-window': 'Солнцезащитная шторка на заднем стекле',
 'roller-blinds-for-rear-side-windows': 'Солнцезащитные шторки в задних дверях',
 'sport-suspension': 'Спортивная подвеска',
 'sport-seats': 'Спортивные передние сиденья',
 'steel-wheels': 'Стальные диски',
 'dark-interior': 'Тёмный салон',
 'fabric-seats': 'Ткань (Материал салона)',
 'tinted-glass': 'Тонированные стекла',
 'third-rear-headrest': 'Третий задний подголовник',
 'third-row-seats': 'Третий ряд сидений',
 'wheel-power': 'Усилитель руля',
 'turnbuckle': 'Фаркоп',
 'folding-front-passenger-seat': 'Функция складывания спинки сиденья пассажира',
 'lock': 'Центральный замок',
 'electronic-gage-panel': 'Электронная приборная панель',
 'mirrors-heat': 'Электрообогрев боковых зеркал',
 'windcleaner-heat': 'Электрообогрев зоны стеклоочистителей',
 'windscreen-heat': 'Электрообогрев лобового стекла',
 'heated-wash-system': 'Электрообогрев форсунок стеклоомывателей',
 'electro-mirrors': 'Электропривод зеркал',
 'electro-trunk': 'Электропривод крышки багажника',
 'electro-rear-seat': 'Электрорегулировка задних сидений',
 'passenger-seat-electric': 'Электрорегулировка передних сидений',
 'e-adjustment-wheel': 'Электрорегулировка руля',
 'driver-seat-electric': 'Электрорегулировка сиденья водителя',
 'auto-mirrors': 'Электроскладывание зеркал',
 'electro-window-back': 'Электростеклоподъёмники задние',
 'electro-window-front': 'Электростеклоподъёмники передние',
 'glonass': 'ЭРА-ГЛОНАСС',
 'ya-auto': 'Яндекс.Авто'}

def hist_and_box (df_column):
    
    """ Для удобства вывод гистограммы и боксплота по одному параметру в ряд
    
        На входе колонка (не название, а сам объект pd.Series)"""
    
    bins= min([10,len(df_column.value_counts())])
    fig = plt.figure(figsize=(12, 4)) 
    ax_1 = fig.add_subplot(121)
    ax_1.set_xlabel(df_column.name)
    df_column.hist(bins=bins, ax=ax_1)
    sns.boxplot(df_column, ax=fig.add_subplot(122))
    plt.show()
    return None